name: 'Terraform Apply'

on: workflow_dispatch

env:
  TF_VERSION: 1.5.0
  ALICLOUD_ACCESS_KEY: ${{ secrets.ALICLOUD_ACCESS_KEY }}
  ALICLOUD_SECRET_KEY: ${{ secrets.ALICLOUD_SECRET_KEY }}

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan  
        run: terraform plan -state=terraform.tfstate -no-color -out=tfplan 

      - name: Terraform Apply
        run: terraform apply -state=terraform.tfstate -auto-approve -input=false
      
      - name: Upload tfstate
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tfstate
          path: terraform.tfstate