name: 'Terraform Plan'

on:
  pull_request:
    branches: [ main ]

env:
  TF_VERSION: 1.5.0
  ALICLOUD_ACCESS_KEY: ${{ secrets.ALICLOUD_ACCESS_KEY }}
  ALICLOUD_SECRET_KEY: ${{ secrets.ALICLOUD_SECRET_KEY }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init --backend=false

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan  
        run: |
          terraform plan -state=terraform.tfstate -no-color -out=tfplan 
          terraform show -no-color tfplan > tfplan_output.txt

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan_output
          path: tfplan_output.txt